Attribute VB_Name = "Datos"

Public Function AgregaDecimales(Numero As String)
    Numero = Round(Numero, 2)
    Dim i As Integer
    i = 1
        Do Until i = Len(Numero)
            If Mid(Numero, i, 1) = "," Then
                Select Case Len(Mid(Numero, i, Len(Numero) - (i)))
                    Case 2
                        AgregaDecimales = Numero
                        Exit Function
                    Case 1
                        AgregaDecimales = Numero & "0"
                        Exit Function
                    Case 0
                        AgregaDecimales = Numero & "00"
                        Exit Function
                End Select
            End If
            i = i + 1
        Loop
    AgregaDecimales = Numero & ",00"
End Function

Public Function GenHTML(Escribania As String, Direccion As String, Telefono As String, partes As String, VEconomico As String, arAncel As String, Certificados As String, aportes1 As String, aportes2 As String, reposicion As String, anotacion As String, goperativo As String, total As String, notros1 As String, otros1 As String, notros2 As String, otros2 As String, notros3 As String, otros3 As String, TipoDeOperacion As String) As String
Dim s As String
s = "<html>" & vbNewLine & "" & vbNewLine & "<body>" & vbNewLine & "" & vbNewLine & "<p align=" & Chr(34) & "center" & Chr(34) & "><font size=" & Chr(34) & "5" & Chr(34) & ">" & Escribania & "</font></p>" & vbNewLine & "<p align=" & Chr(34) & "center" & Chr(34) & "><font size=" & Chr(34) & "4" & Chr(34) & ">" & Direccion & "</font></p>" & vbNewLine & "<p align=" & Chr(34) & "center" & Chr(34) & "><font size=" & Chr(34) & "4" & Chr(34) & ">" & Telefono & "</font></p>" & vbNewLine & "<p align=" & Chr(34) & "center" & Chr(34) & "><font size=" & Chr(34) & "4" & Chr(34) & ">Presupuesto - " & TipoDeOperacion & "</font></p>" & vbNewLine & "<p align=" & Chr(34) & "center" & Chr(34) & ">" & partes & "</p>" & vbNewLine & "<p align=" & Chr(34) & "center" & Chr(34) & ">&nbsp;</p>" & vbNewLine & "<div align=" & Chr(34) & "center" & Chr(34) & " style=" & Chr(34) & "width: 383; height: 209" & Chr(34) & ">" & vbNewLine & "  <center>" & vbNewLine & "  <table border=" & _
Chr(34) & "1" & Chr(34) & " cellpadding=" & Chr(34) & "0" & Chr(34) & " cellspacing=" & Chr(34) & "0" & Chr(34) & " style=" & Chr(34) & "border-collapse: collapse" & Chr(34) & " bordercolor=" & Chr(34) & "#FFFFFF" & Chr(34) & " width=" & Chr(34) & "256" & Chr(34) & " height=" & Chr(34) & "1" & Chr(34) & " id=" & Chr(34) & "AutoNumber1" & Chr(34) & " align=" & Chr(34) & "right" & Chr(34) & ">" & vbNewLine & "    <tr>" & vbNewLine & "      <td width=" & Chr(34) & "264" & Chr(34) & " height=" & Chr(34) & "13" & Chr(34) & " align=" & Chr(34) & "center" & Chr(34) & ">" & vbNewLine & "      <p align=" & Chr(34) & "right" & Chr(34) & ">Valor económico:</td>" & vbNewLine & "      <td width=" & Chr(34) & "79" & Chr(34) & " height=" & Chr(34) & "13" & Chr(34) & " align=" & Chr(34) & "center" & Chr(34) & ">" & vbNewLine & "      <p align=" & Chr(34) & "right" & Chr(34) & "><span lang=" & Chr(34) & "es" & Chr(34) & ">$</span></td>" & vbNewLine & "      <td width=" & Chr(34) & "173" & Chr(34) & " height=" & Chr(34) & _
"13" & Chr(34) & " align=" & Chr(34) & "center" & Chr(34) & ">" & vbNewLine & "      <p align=" & Chr(34) & "right" & Chr(34) & "><span lang=" & Chr(34) & "es" & Chr(34) & ">" & VEconomico & "</span></td>" & vbNewLine & "    </tr>" & vbNewLine & "    <tr>" & vbNewLine & "      <td width=" & Chr(34) & "264" & Chr(34) & " height=" & Chr(34) & "14" & Chr(34) & " align=" & Chr(34) & "center" & Chr(34) & ">" & vbNewLine & "      <p align=" & Chr(34) & "right" & Chr(34) & ">Arancel:</td>" & vbNewLine & "      <td width=" & Chr(34) & "79" & Chr(34) & " height=" & Chr(34) & "14" & Chr(34) & " align=" & Chr(34) & "center" & Chr(34) & ">" & vbNewLine & "      <p align=" & Chr(34) & "right" & Chr(34) & "><span lang=" & Chr(34) & "es" & Chr(34) & ">$</span></td>" & vbNewLine & "      <td width=" & Chr(34) & "173" & Chr(34) & " height=" & Chr(34) & "14" & Chr(34) & " align=" & Chr(34) & "center" & Chr(34) & ">" & vbNewLine & "      <p align=" & Chr(34) & "right" & Chr(34) & "><span lang=" & Chr(34) & "es" & Chr(34) & _
">" & arAncel & "</span></td>" & vbNewLine & "    </tr>" & vbNewLine & "    <tr>" & vbNewLine & "      <td width=" & Chr(34) & "264" & Chr(34) & " height=" & Chr(34) & "17" & Chr(34) & " align=" & Chr(34) & "center" & Chr(34) & ">" & vbNewLine & "      <p align=" & Chr(34) & "right" & Chr(34) & ">Certificados:</td>" & vbNewLine & "      <td width=" & Chr(34) & "79" & Chr(34) & " height=" & Chr(34) & "17" & Chr(34) & " align=" & Chr(34) & "center" & Chr(34) & ">" & vbNewLine & "      <p align=" & Chr(34) & "right" & Chr(34) & "><span lang=" & Chr(34) & "es" & Chr(34) & ">$</span></td>" & vbNewLine & "      <td width=" & Chr(34) & "173" & Chr(34) & " height=" & Chr(34) & "17" & Chr(34) & " align=" & Chr(34) & "center" & Chr(34) & ">" & vbNewLine & "      <p align=" & Chr(34) & "right" & Chr(34) & "><span lang=" & Chr(34) & "es" & Chr(34) & ">" & Certificados & "</span></td>" & vbNewLine & "    </tr>" & vbNewLine & "    <tr>" & vbNewLine & "      <td width=" & Chr(34) & "264" & Chr(34) & " height=" & _
Chr(34) & "12" & Chr(34) & " align=" & Chr(34) & "center" & _
Chr(34) & ">" & vbNewLine & "      <p align=" & Chr(34) & "right" & Chr(34) & ">Aportes (a):</td>" & vbNewLine & "      <td width=" & Chr(34) & "79" & Chr(34) & " height=" & Chr(34) & "12" & Chr(34) & " align=" & Chr(34) & "center" & Chr(34) & ">" & vbNewLine & "      <p align=" & Chr(34) & "right" & Chr(34) & "><span lang=" & Chr(34) & "es" & Chr(34) & ">$</span></td>" & vbNewLine & "      <td width=" & Chr(34) & "173" & Chr(34) & " height=" & Chr(34) & "12" & Chr(34) & " align=" & Chr(34) & "center" & Chr(34) & ">" & vbNewLine & "      <p align=" & Chr(34) & "right" & Chr(34) & "><span lang=" & Chr(34) & "es" & Chr(34) & ">" & aportes1 & "</span></td>" & vbNewLine & "    </tr>" & vbNewLine & "    <tr>" & vbNewLine & "      <td width=" & Chr(34) & "264" & Chr(34) & " height=" & Chr(34) & "14" & Chr(34) & " align=" & Chr(34) & "center" & Chr(34) & ">" & vbNewLine & "      <p align=" & Chr(34) & "right" & Chr(34) & ">Aportes (<span lang=" & Chr(34) & "es" & Chr(34) & ">b</span>):</td>" & vbNewLine & "" & _
"<td width=" & Chr(34) & "79" & Chr(34) & " height=" & Chr(34) & "14" & Chr(34) & " align=" & Chr(34) & "center" & Chr(34) & ">" & vbNewLine & "      <p align=" & Chr(34) & "right" & Chr(34) & "><span lang=" & Chr(34) & "es" & Chr(34) & ">$</span></td>" & vbNewLine & "      <td width=" & Chr(34) & "173" & Chr(34) & " height=" & Chr(34) & "14" & Chr(34) & " align=" & Chr(34) & "center" & Chr(34) & ">" & vbNewLine & "      <p align=" & Chr(34) & "right" & Chr(34) & "><span lang=" & Chr(34) & "es" & Chr(34) & ">" & aportes2 & "</span></td>" & vbNewLine & "    </tr>" & vbNewLine & "    <tr>" & vbNewLine & "      <td width=" & Chr(34) & "264" & Chr(34) & " height=" & Chr(34) & "10" & Chr(34) & " align=" & Chr(34) & "center" & Chr(34) & ">" & vbNewLine & "      <p align=" & Chr(34) & "right" & Chr(34) & "><span lang=" & Chr(34) & "es" & Chr(34) & ">Reposición:</span></td>" & vbNewLine & "      <td width=" & Chr(34) & "79" & Chr(34) & " height=" & Chr(34) & "10" & Chr(34) & " align=" & Chr(34) & "center" & _
Chr(34) & _
">" & _
vbNewLine & "      <p align=" & Chr(34) & "right" & Chr(34) & "><span lang=" & Chr(34) & "es" & Chr(34) & ">$</span></td>" & vbNewLine & "      <td width=" & Chr(34) & "173" & Chr(34) & " height=" & Chr(34) & "10" & Chr(34) & " align=" & Chr(34) & "center" & Chr(34) & ">" & vbNewLine & "      <p align=" & Chr(34) & "right" & Chr(34) & "><span lang=" & Chr(34) & "es" & Chr(34) & ">" & reposicion & "</span></td>" & vbNewLine & "    </tr>" & vbNewLine & "    <tr>" & vbNewLine & "      <td width=" & Chr(34) & "264" & Chr(34) & " height=" & Chr(34) & "11" & Chr(34) & " align=" & Chr(34) & "center" & Chr(34) & ">" & vbNewLine & "      <p align=" & Chr(34) & "right" & Chr(34) & "><span lang=" & Chr(34) & "es" & Chr(34) & ">Anotación:</span></td>" & vbNewLine & "      <td width=" & Chr(34) & "79" & Chr(34) & " height=" & Chr(34) & "11" & Chr(34) & " align=" & Chr(34) & "center" & Chr(34) & ">" & vbNewLine & "      <p align=" & Chr(34) & "right" & Chr(34) & "><span lang=" & Chr(34) & "es" & Chr(34) & _
">$</span></td>" & _
vbNewLine & "      <td width=" & Chr(34) & "173" & Chr(34) & " height=" & Chr(34) & "11" & Chr(34) & " align=" & Chr(34) & "center" & Chr(34) & ">" & vbNewLine & "      <p align=" & Chr(34) & "right" & Chr(34) & "><span lang=" & Chr(34) & "es" & Chr(34) & ">" & anotacion & "</span></td>" & vbNewLine & "    </tr>" & vbNewLine & "    <tr>" & vbNewLine & "      <td width=" & Chr(34) & "264" & Chr(34) & " height=" & Chr(34) & "9" & Chr(34) & " align=" & Chr(34) & "center" & Chr(34) & ">" & vbNewLine & "      <p align=" & Chr(34) & "right" & Chr(34) & "><span lang=" & Chr(34) & "es" & Chr(34) & ">Gasto operativo:</span></td>" & vbNewLine & "      <td width=" & Chr(34) & "79" & Chr(34) & " height=" & Chr(34) & "9" & Chr(34) & " align=" & Chr(34) & "center" & Chr(34) & ">" & vbNewLine & "      <p align=" & Chr(34) & "right" & Chr(34) & "><span lang=" & Chr(34) & "es" & Chr(34) & ">$</span></td>" & vbNewLine & "      <td width=" & Chr(34) & "173" & Chr(34) & " height=" & Chr(34) & "9" & Chr(34) & " align=" & _
Chr(34) & "center" & _
Chr(34) & ">" & vbNewLine & "      <p align=" & Chr(34) & "right" & Chr(34) & "><span lang=" & Chr(34) & "es" & Chr(34) & ">" & goperativo & "</span></td>" & vbNewLine & "    </tr>" & vbNewLine
If Not otros1 = "0,00" Then
s = s & "    <tr>" & vbNewLine & "      <td width=" & Chr(34) & "264" & Chr(34) & " height=" & Chr(34) & "10" & Chr(34) & " align=" & Chr(34) & "center" & Chr(34) & ">" & vbNewLine & "      <p align=" & Chr(34) & "right" & Chr(34) & "><span lang=" & Chr(34) & "es" & Chr(34) & ">" & notros1 & "</span></td>" & vbNewLine & "      <td width=" & Chr(34) & "79" & Chr(34) & " height=" & Chr(34) & "10" & Chr(34) & " align=" & Chr(34) & "center" & Chr(34) & ">" & vbNewLine & "      <p align=" & Chr(34) & "right" & Chr(34) & "><span lang=" & Chr(34) & "es" & Chr(34) & ">$</span></td>" & vbNewLine & "      <td width=" & Chr(34) & "173" & Chr(34) & " height=" & Chr(34) & "10" & Chr(34) & " align=" & Chr(34) & "center" & Chr(34) & ">" & vbNewLine & "      <p align=" & Chr(34) & "right" & Chr(34) & "><span lang=" & Chr(34) & "es" & Chr(34) & ">" & otros1 & "</span></td>" & vbNewLine & "    </tr>"
End If
If Not otros2 = "0,00" Then
s = s & "    <tr>" & vbNewLine & "      <td width=" & Chr(34) & "264" & Chr(34) & " height=" & Chr(34) & "10" & Chr(34) & " align=" & Chr(34) & "center" & Chr(34) & ">" & vbNewLine & "      <p align=" & Chr(34) & "right" & Chr(34) & "><span lang=" & Chr(34) & "es" & Chr(34) & ">" & notros2 & "</span></td>" & vbNewLine & "      <td width=" & Chr(34) & "79" & Chr(34) & " height=" & Chr(34) & "10" & Chr(34) & " align=" & Chr(34) & "center" & Chr(34) & ">" & vbNewLine & "      <p align=" & Chr(34) & "right" & Chr(34) & "><span lang=" & Chr(34) & "es" & Chr(34) & ">$</span></td>" & vbNewLine & "      <td width=" & Chr(34) & "173" & Chr(34) & " height=" & Chr(34) & "10" & Chr(34) & " align=" & Chr(34) & "center" & Chr(34) & ">" & vbNewLine & "      <p align=" & Chr(34) & "right" & Chr(34) & "><span lang=" & Chr(34) & "es" & Chr(34) & ">" & otros2 & "</span></td>" & vbNewLine & "    </tr>"
End If
If Not otros3 = "0,00" Then
s = s & "    <tr>" & vbNewLine & "      <td width=" & Chr(34) & "264" & Chr(34) & " height=" & Chr(34) & "10" & Chr(34) & " align=" & Chr(34) & "center" & Chr(34) & ">" & vbNewLine & "      <p align=" & Chr(34) & "right" & Chr(34) & "><span lang=" & Chr(34) & "es" & Chr(34) & ">" & notros3 & "</span></td>" & vbNewLine & "      <td width=" & Chr(34) & "79" & Chr(34) & " height=" & Chr(34) & "10" & Chr(34) & " align=" & Chr(34) & "center" & Chr(34) & ">" & vbNewLine & "      <p align=" & Chr(34) & "right" & Chr(34) & "><span lang=" & Chr(34) & "es" & Chr(34) & ">$</span></td>" & vbNewLine & "      <td width=" & Chr(34) & "173" & Chr(34) & " height=" & Chr(34) & "10" & Chr(34) & " align=" & Chr(34) & "center" & Chr(34) & ">" & vbNewLine & "      <p align=" & Chr(34) & "right" & Chr(34) & "><span lang=" & Chr(34) & "es" & Chr(34) & ">" & otros3 & "</span></td>" & vbNewLine & "    </tr>"
End If
s = s & "    <tr>" & vbNewLine & "      <td width=" & Chr(34) & "264" & Chr(34) & " height=" & Chr(34) & "8" & Chr(34) & " align=" & Chr(34) & "center" & Chr(34) & ">" & vbNewLine & "      </td>" & vbNewLine & "      <td width=" & Chr(34) & "79" & Chr(34) & " height=" & Chr(34) & "8" & Chr(34) & " align=" & Chr(34) & "center" & Chr(34) & ">" & vbNewLine & "      </td>" & vbNewLine & "      <td width=" & Chr(34) & "173" & Chr(34) & " height=" & Chr(34) & "8" & Chr(34) & " align=" & Chr(34) & "center" & Chr(34) & ">" & vbNewLine & "      </td>" & vbNewLine & "    </tr>" & vbNewLine & "    <tr>" & vbNewLine & "      <td width=" & Chr(34) & "264" & Chr(34) & " height=" & Chr(34) & "16" & Chr(34) & " align=" & Chr(34) & "center" & Chr(34) & ">" & vbNewLine & "      <p align=" & Chr(34) & "right" & Chr(34) & "><span lang=" & _
Chr(34) & _
"es" & Chr(34) & ">Total:</span></td>" & vbNewLine & "      <td width=" & Chr(34) & "79" & Chr(34) & " height=" & Chr(34) & "16" & Chr(34) & " align=" & Chr(34) & "center" & Chr(34) & ">" & vbNewLine & "      <p align=" & Chr(34) & "right" & Chr(34) & "><span lang=" & Chr(34) & "es" & Chr(34) & ">$</span></td>" & vbNewLine & "      <td width=" & Chr(34) & "173" & Chr(34) & " height=" & Chr(34) & "16" & Chr(34) & " align=" & Chr(34) & "center" & Chr(34) & ">" & vbNewLine & "      <p align=" & Chr(34) & "right" & Chr(34) & "><span lang=" & Chr(34) & "es" & Chr(34) & ">" & total & "</span></td>" & vbNewLine & "    </tr>" & vbNewLine & "  </table>" & vbNewLine & "  <p>&nbsp;</p>" & vbNewLine & "  <p>&nbsp;</p>" & vbNewLine & "  <p>&nbsp;</p>" & vbNewLine & "  <p>&nbsp;</p>" & vbNewLine & "  <p>&nbsp;</p>" & vbNewLine & "  <p>&nbsp;</p>" & vbNewLine & "  </center>" & vbNewLine & "</div>" & vbNewLine & "" & vbNewLine & "</body>" & vbNewLine & "" & vbNewLine & "</html>"
GenHTML = s
End Function
Public Function GenHTMLDonacion(Escribania As String, Direccion As String, Telefono As String, partes As String, VEconomico As String, arAncel As String, Certificados As String, aportes1 As String, aportes2 As String, anotacion As String, goperativo As String, total As String, notros1 As String, otros1 As String, notros2 As String, otros2 As String, notros3 As String, otros3 As String) As String
Dim s As String
s = "<html>" & vbNewLine & "" & vbNewLine & "<body>" & vbNewLine & "" & vbNewLine & "<p align=" & Chr(34) & "center" & Chr(34) & "><font size=" & Chr(34) & "5" & Chr(34) & ">" & Escribania & "</font></p>" & vbNewLine & "<p align=" & Chr(34) & "center" & Chr(34) & "><font size=" & Chr(34) & "4" & Chr(34) & ">" & Direccion & "</font></p>" & vbNewLine & "<p align=" & Chr(34) & "center" & Chr(34) & "><font size=" & Chr(34) & "4" & Chr(34) & ">" & Telefono & "</font></p>" & vbNewLine & "<p align=" & Chr(34) & "center" & Chr(34) & "><font size=" & Chr(34) & "4" & Chr(34) & ">Presupuesto - Donación</font></p>" & vbNewLine & "<p align=" & Chr(34) & "center" & Chr(34) & ">" & partes & "</p>" & vbNewLine & "<p align=" & Chr(34) & "center" & Chr(34) & ">&nbsp;</p>" & vbNewLine & "<div align=" & Chr(34) & "center" & Chr(34) & " style=" & Chr(34) & "width: 383; height: 209" & Chr(34) & ">" & vbNewLine & "  <center>" & vbNewLine & "  <table border=" & _
Chr(34) & "1" & Chr(34) & " cellpadding=" & Chr(34) & "0" & Chr(34) & " cellspacing=" & Chr(34) & "0" & Chr(34) & " style=" & Chr(34) & "border-collapse: collapse" & Chr(34) & " bordercolor=" & Chr(34) & "#FFFFFF" & Chr(34) & " width=" & Chr(34) & "256" & Chr(34) & " height=" & Chr(34) & "1" & Chr(34) & " id=" & Chr(34) & "AutoNumber1" & Chr(34) & " align=" & Chr(34) & "right" & Chr(34) & ">" & vbNewLine & "    <tr>" & vbNewLine & "      <td width=" & Chr(34) & "264" & Chr(34) & " height=" & Chr(34) & "13" & Chr(34) & " align=" & Chr(34) & "center" & Chr(34) & ">" & vbNewLine & "      <p align=" & Chr(34) & "right" & Chr(34) & ">Valor económico:</td>" & vbNewLine & "      <td width=" & Chr(34) & "79" & Chr(34) & " height=" & Chr(34) & "13" & Chr(34) & " align=" & Chr(34) & "center" & Chr(34) & ">" & vbNewLine & "      <p align=" & Chr(34) & "right" & Chr(34) & "><span lang=" & Chr(34) & "es" & Chr(34) & ">$</span></td>" & vbNewLine & "      <td width=" & Chr(34) & "173" & Chr(34) & " height=" & Chr(34) & _
"13" & Chr(34) & " align=" & Chr(34) & "center" & Chr(34) & ">" & vbNewLine & "      <p align=" & Chr(34) & "right" & Chr(34) & "><span lang=" & Chr(34) & "es" & Chr(34) & ">" & VEconomico & "</span></td>" & vbNewLine & "    </tr>" & vbNewLine & "    <tr>" & vbNewLine & "      <td width=" & Chr(34) & "264" & Chr(34) & " height=" & Chr(34) & "14" & Chr(34) & " align=" & Chr(34) & "center" & Chr(34) & ">" & vbNewLine & "      <p align=" & Chr(34) & "right" & Chr(34) & ">Arancel:</td>" & vbNewLine & "      <td width=" & Chr(34) & "79" & Chr(34) & " height=" & Chr(34) & "14" & Chr(34) & " align=" & Chr(34) & "center" & Chr(34) & ">" & vbNewLine & "      <p align=" & Chr(34) & "right" & Chr(34) & "><span lang=" & Chr(34) & "es" & Chr(34) & ">$</span></td>" & vbNewLine & "      <td width=" & Chr(34) & "173" & Chr(34) & " height=" & Chr(34) & "14" & Chr(34) & " align=" & Chr(34) & "center" & Chr(34) & ">" & vbNewLine & "      <p align=" & Chr(34) & "right" & Chr(34) & "><span lang=" & Chr(34) & "es" & Chr(34) & _
">" & arAncel & "</span></td>" & vbNewLine & "    </tr>" & vbNewLine & "    <tr>" & vbNewLine & "      <td width=" & Chr(34) & "264" & Chr(34) & " height=" & Chr(34) & "17" & Chr(34) & " align=" & Chr(34) & "center" & Chr(34) & ">" & vbNewLine & "      <p align=" & Chr(34) & "right" & Chr(34) & ">Certificados:</td>" & vbNewLine & "      <td width=" & Chr(34) & "79" & Chr(34) & " height=" & Chr(34) & "17" & Chr(34) & " align=" & Chr(34) & "center" & Chr(34) & ">" & vbNewLine & "      <p align=" & Chr(34) & "right" & Chr(34) & "><span lang=" & Chr(34) & "es" & Chr(34) & ">$</span></td>" & vbNewLine & "      <td width=" & Chr(34) & "173" & Chr(34) & " height=" & Chr(34) & "17" & Chr(34) & " align=" & Chr(34) & "center" & Chr(34) & ">" & vbNewLine & "      <p align=" & Chr(34) & "right" & Chr(34) & "><span lang=" & Chr(34) & "es" & Chr(34) & ">" & Certificados & "</span></td>" & vbNewLine & "    </tr>" & vbNewLine & "    <tr>" & vbNewLine & "      <td width=" & Chr(34) & "264" & Chr(34) & " height=" & _
Chr(34) & "12" & Chr(34) & " align=" & Chr(34) & "center" & _
Chr(34) & ">" & vbNewLine & "      <p align=" & Chr(34) & "right" & Chr(34) & ">Aportes (a):</td>" & vbNewLine & "      <td width=" & Chr(34) & "79" & Chr(34) & " height=" & Chr(34) & "12" & Chr(34) & " align=" & Chr(34) & "center" & Chr(34) & ">" & vbNewLine & "      <p align=" & Chr(34) & "right" & Chr(34) & "><span lang=" & Chr(34) & "es" & Chr(34) & ">$</span></td>" & vbNewLine & "      <td width=" & Chr(34) & "173" & Chr(34) & " height=" & Chr(34) & "12" & Chr(34) & " align=" & Chr(34) & "center" & Chr(34) & ">" & vbNewLine & "      <p align=" & Chr(34) & "right" & Chr(34) & "><span lang=" & Chr(34) & "es" & Chr(34) & ">" & aportes1 & "</span></td>" & vbNewLine & "    </tr>" & vbNewLine & "    <tr>" & vbNewLine & "      <td width=" & Chr(34) & "264" & Chr(34) & " height=" & Chr(34) & "14" & Chr(34) & " align=" & Chr(34) & "center" & Chr(34) & ">" & vbNewLine & "      <p align=" & Chr(34) & "right" & Chr(34) & ">Aportes (<span lang=" & Chr(34) & "es" & Chr(34) & ">b</span>):</td>" & vbNewLine & "" & _
"<td width=" & Chr(34) & "79" & Chr(34) & " height=" & Chr(34) & "14" & Chr(34) & " align=" & Chr(34) & "center" & Chr(34) & ">" & vbNewLine & "      <p align=" & Chr(34) & "right" & Chr(34) & "><span lang=" & Chr(34) & "es" & Chr(34) & ">$</span></td>" & vbNewLine & "      <td width=" & Chr(34) & "173" & Chr(34) & " height=" & Chr(34) & "14" & Chr(34) & " align=" & Chr(34) & "center" & Chr(34) & ">" & vbNewLine & "      <p align=" & Chr(34) & "right" & Chr(34) & "><span lang=" & Chr(34) & "es" & Chr(34) & ">" & aportes2 & "</span></td>" & vbNewLine & "    </tr>" & vbNewLine & "    <tr>" & vbNewLine & "      <td width=" & Chr(34) & "264" & Chr(34) & " height=" & Chr(34) & "11" & Chr(34) & " align=" & Chr(34) & "center" & Chr(34) & ">" & vbNewLine & "      <p align=" & Chr(34) & "right" & Chr(34) & "><span lang=" & Chr(34) & "es" & Chr(34) & ">Anotación:</span></td>" & vbNewLine & "      <td width=" & Chr(34) & "79" & Chr(34) & " height=" & Chr(34) & "11" & Chr(34) & " align=" & Chr(34) & "center" & _
Chr(34) & _
">" & vbNewLine & "      <p align=" & Chr(34) & "right" & Chr(34) & "><span lang=" & Chr(34) & "es" & Chr(34) & _
">$</span></td>" & _
vbNewLine & "      <td width=" & Chr(34) & "173" & Chr(34) & " height=" & Chr(34) & "11" & Chr(34) & " align=" & Chr(34) & "center" & Chr(34) & ">" & vbNewLine & "      <p align=" & Chr(34) & "right" & Chr(34) & "><span lang=" & Chr(34) & "es" & Chr(34) & ">" & anotacion & "</span></td>" & vbNewLine & "    </tr>" & vbNewLine & "    <tr>" & vbNewLine & "      <td width=" & Chr(34) & "264" & Chr(34) & " height=" & Chr(34) & "9" & Chr(34) & " align=" & Chr(34) & "center" & Chr(34) & ">" & vbNewLine & "      <p align=" & Chr(34) & "right" & Chr(34) & "><span lang=" & Chr(34) & "es" & Chr(34) & ">Gasto operativo:</span></td>" & vbNewLine & "      <td width=" & Chr(34) & "79" & Chr(34) & " height=" & Chr(34) & "9" & Chr(34) & " align=" & Chr(34) & "center" & Chr(34) & ">" & vbNewLine & "      <p align=" & Chr(34) & "right" & Chr(34) & "><span lang=" & Chr(34) & "es" & Chr(34) & ">$</span></td>" & vbNewLine & "      <td width=" & Chr(34) & "173" & Chr(34) & " height=" & Chr(34) & "9" & Chr(34) & " align=" & _
Chr(34) & "center" & _
Chr(34) & ">" & vbNewLine & "      <p align=" & Chr(34) & "right" & Chr(34) & "><span lang=" & Chr(34) & "es" & Chr(34) & ">" & goperativo & "</span></td>" & vbNewLine & "    </tr>" & vbNewLine
If Not otros1 = "0,00" Then
s = s & "    <tr>" & vbNewLine & "      <td width=" & Chr(34) & "264" & Chr(34) & " height=" & Chr(34) & "10" & Chr(34) & " align=" & Chr(34) & "center" & Chr(34) & ">" & vbNewLine & "      <p align=" & Chr(34) & "right" & Chr(34) & "><span lang=" & Chr(34) & "es" & Chr(34) & ">" & notros1 & "</span></td>" & vbNewLine & "      <td width=" & Chr(34) & "79" & Chr(34) & " height=" & Chr(34) & "10" & Chr(34) & " align=" & Chr(34) & "center" & Chr(34) & ">" & vbNewLine & "      <p align=" & Chr(34) & "right" & Chr(34) & "><span lang=" & Chr(34) & "es" & Chr(34) & ">$</span></td>" & vbNewLine & "      <td width=" & Chr(34) & "173" & Chr(34) & " height=" & Chr(34) & "10" & Chr(34) & " align=" & Chr(34) & "center" & Chr(34) & ">" & vbNewLine & "      <p align=" & Chr(34) & "right" & Chr(34) & "><span lang=" & Chr(34) & "es" & Chr(34) & ">" & otros1 & "</span></td>" & vbNewLine & "    </tr>"
End If
If Not otros2 = "0,00" Then
s = s & "    <tr>" & vbNewLine & "      <td width=" & Chr(34) & "264" & Chr(34) & " height=" & Chr(34) & "10" & Chr(34) & " align=" & Chr(34) & "center" & Chr(34) & ">" & vbNewLine & "      <p align=" & Chr(34) & "right" & Chr(34) & "><span lang=" & Chr(34) & "es" & Chr(34) & ">" & notros2 & "</span></td>" & vbNewLine & "      <td width=" & Chr(34) & "79" & Chr(34) & " height=" & Chr(34) & "10" & Chr(34) & " align=" & Chr(34) & "center" & Chr(34) & ">" & vbNewLine & "      <p align=" & Chr(34) & "right" & Chr(34) & "><span lang=" & Chr(34) & "es" & Chr(34) & ">$</span></td>" & vbNewLine & "      <td width=" & Chr(34) & "173" & Chr(34) & " height=" & Chr(34) & "10" & Chr(34) & " align=" & Chr(34) & "center" & Chr(34) & ">" & vbNewLine & "      <p align=" & Chr(34) & "right" & Chr(34) & "><span lang=" & Chr(34) & "es" & Chr(34) & ">" & otros2 & "</span></td>" & vbNewLine & "    </tr>"
End If
If Not otros3 = "0,00" Then
s = s & "    <tr>" & vbNewLine & "      <td width=" & Chr(34) & "264" & Chr(34) & " height=" & Chr(34) & "10" & Chr(34) & " align=" & Chr(34) & "center" & Chr(34) & ">" & vbNewLine & "      <p align=" & Chr(34) & "right" & Chr(34) & "><span lang=" & Chr(34) & "es" & Chr(34) & ">" & notros3 & "</span></td>" & vbNewLine & "      <td width=" & Chr(34) & "79" & Chr(34) & " height=" & Chr(34) & "10" & Chr(34) & " align=" & Chr(34) & "center" & Chr(34) & ">" & vbNewLine & "      <p align=" & Chr(34) & "right" & Chr(34) & "><span lang=" & Chr(34) & "es" & Chr(34) & ">$</span></td>" & vbNewLine & "      <td width=" & Chr(34) & "173" & Chr(34) & " height=" & Chr(34) & "10" & Chr(34) & " align=" & Chr(34) & "center" & Chr(34) & ">" & vbNewLine & "      <p align=" & Chr(34) & "right" & Chr(34) & "><span lang=" & Chr(34) & "es" & Chr(34) & ">" & otros3 & "</span></td>" & vbNewLine & "    </tr>"
End If
s = s & "    <tr>" & vbNewLine & "      <td width=" & Chr(34) & "264" & Chr(34) & " height=" & Chr(34) & "8" & Chr(34) & " align=" & Chr(34) & "center" & Chr(34) & ">" & vbNewLine & "      </td>" & vbNewLine & "      <td width=" & Chr(34) & "79" & Chr(34) & " height=" & Chr(34) & "8" & Chr(34) & " align=" & Chr(34) & "center" & Chr(34) & ">" & vbNewLine & "      </td>" & vbNewLine & "      <td width=" & Chr(34) & "173" & Chr(34) & " height=" & Chr(34) & "8" & Chr(34) & " align=" & Chr(34) & "center" & Chr(34) & ">" & vbNewLine & "      </td>" & vbNewLine & "    </tr>" & vbNewLine & "    <tr>" & vbNewLine & "      <td width=" & Chr(34) & "264" & Chr(34) & " height=" & Chr(34) & "16" & Chr(34) & " align=" & Chr(34) & "center" & Chr(34) & ">" & vbNewLine & "      <p align=" & Chr(34) & "right" & Chr(34) & "><span lang=" & _
Chr(34) & _
"es" & Chr(34) & ">Total:</span></td>" & vbNewLine & "      <td width=" & Chr(34) & "79" & Chr(34) & " height=" & Chr(34) & "16" & Chr(34) & " align=" & Chr(34) & "center" & Chr(34) & ">" & vbNewLine & "      <p align=" & Chr(34) & "right" & Chr(34) & "><span lang=" & Chr(34) & "es" & Chr(34) & ">$</span></td>" & vbNewLine & "      <td width=" & Chr(34) & "173" & Chr(34) & " height=" & Chr(34) & "16" & Chr(34) & " align=" & Chr(34) & "center" & Chr(34) & ">" & vbNewLine & "      <p align=" & Chr(34) & "right" & Chr(34) & "><span lang=" & Chr(34) & "es" & Chr(34) & ">" & total & "</span></td>" & vbNewLine & "    </tr>" & vbNewLine & "  </table>" & vbNewLine & "  <p>&nbsp;</p>" & vbNewLine & "  <p>&nbsp;</p>" & vbNewLine & "  <p>&nbsp;</p>" & vbNewLine & "  <p>&nbsp;</p>" & vbNewLine & "  <p>&nbsp;</p>" & vbNewLine & "  <p>&nbsp;</p>" & vbNewLine & "  </center>" & vbNewLine & "</div>" & vbNewLine & "" & vbNewLine & "</body>" & vbNewLine & "" & vbNewLine & "</html>"
GenHTMLDonacion = s
End Function

